limo-sum/anser

- public/data/data.json
- src/Pages/AccountInfo.js
- src/Routes.js
- src/Styles/reset.css
AccountPage 구현 완료 (Nav & Footer 완료 시 병합 필요)
> Add: AccountInfo Page 구현

- public/index.html
- src/Pages/SignIn.js
- src/Routes.js
> Add: SignIn Page Layout 구현 완료

- package-lock.json
- src/Components/Footer.js
- src/Routes.js
> add: footer 레이아웃 완성

- src/Components/Footer/Footer.js
- src/Pages/SignUp/Signup.js
- src/config.js
diplay props 값에 따른 스타일 컴포넌트 통합.
footer 코드 리팩토링과 signup 코드 리팩토링 진행하였음.
> Refactor: 코드 리뷰에 따른 재재수정

- src/Pages/CRSP.js
- src/Pages/Components/CRSP/StepOne.js
add: CRSP Step1 완성.
-달력 체크범위는 교수님과 상담하여 없앨지 결정하겠음.
> add: CRSP Step1 완성

- package-lock.json
- package.json
- public/data/crsptab.json
- src/Pages/Components/CRSP/Search.js
- src/Pages/Components/CRSP/StepThree.js
- src/Pages/Components/CRSP/StepThreeSelect.js
- src/Pages/Components/CRSP/StepThreeSelected.js
Step 3 레이아웃입니다.
카테고리 클릭 시 색 변경, 추가된 요소 숫자 증가 등
추가적으로 수정 예정입니다.
> Add: StepThree Layout

- public/data/savedqueries.json
- src/Pages/Components/CRSP/StepThreeContents.js
- src/Pages/SavedQueries/SavedQueries.js
- src/Routes.js
SavedQueries Page Layout 완성
- 오름차순/내림차순 기능 구현
- Rerun & Delete는 Layout만 구현 
- Saved Codes는 추가 구현 사항으로 이번 Commit에는 포함되지 않음
- StepThreeLayout Review는 해당 PR merge 후 반영 예정
> Add: SavedQueries Page Layout 완성

- src/Pages/CRSP.js
- src/Pages/SavedQueries/SavedQueries.js
CRSP Title 추가 
CRSP Title (DailyStock) 추가
> Refactor: CRSP Title 추가

- public/data/crsptab.json
- public/index.html
- src/Pages/Components/CRSP/StepThreeSelect.js
- src/Pages/Components/Main/ContactMap.js
- src/Pages/Components/Main/ContactUs.js
- src/Pages/UserInfo/AccountInfo.js
>### Fix: GoogleMap 오류 수정
>#### GoogleMapAPI 오류 수정 :
- Google-map-react 설치
- 결제 계정 등록
- 위치 및 크기 조정
>#### CRSP Step3 데이터 수정 (물음표 클릭 시 설명 모달 추가)
>#### AccountInfo 메일 클릭 시 Main으로 이동하는 코드 삭제 (태그 변경)
> Fix: GoogleMap 오류 수정

- src/Components/Nav/MainNav.js
- src/Components/Nav/Nav.js
**[2020. 08. 29(토)]**
- 링크 태그 오동작 수정
**[2020. 08. 29(토)]**
- 메인 페이지에서는 제대로 동작하지만 페이지를 이동할 경우 오동작 하던 버그 수정
> Fix: 링크 태그 오동작 수정

- public/data/stepThreeCategory.json
- src/Pages/Components/CRSP/StepThreeContents.js
- src/Pages/Components/CRSP/StepThreeSelect.js
- src/Pages/Components/CRSP/StepThreeSelected.js
- src/Pages/Components/Main/ContactMap.js
- src/Styles/style.js
Refactor: sessionStorage 추가 함수
- selected 배열 sessionStorage.setItem (click과 동시에 반영) 함수 추가
- GoogleMapAPI 크기 오류 수정
- 카테고리 이름 오류 수정 (SelectAll → SearchAll)
- 불변성 : state data 이용 시 기존의 배열을 수정하지 않고 새로운 배열을 사용하도록 onClick function 변경
(이렇게 하지 않을 시 상태의 변화를 감지하지 못해 selected 취소 시 sessionStorage의 데이터가 업데이트 되지 않음)
- StepThreeContents 재사용 Style 별도 파일로 분리
> Refactor: sessionStorage 추가 함수

- src/Pages/CRSP.js
- src/Pages/Components/CRSP/CodeLookup.js
- src/Pages/Components/CRSP/Search.js
- src/Pages/Components/CRSP/StepOne.js
- src/Pages/Components/CRSP/TableData.js
**[2020. 08. 30(일)]**
- session storage에 데이터 저장하는 함수 추가
**[2020. 08. 30(일)]**
- session storage에 데이터 저장하는 함수 추가
- 선택한 데이터의 갯수에 따라 다른 alert창 팝업하는 기능 추가
- 아무것도 선택하지 않았을 시 실행 방지 기능 추가
- 전체 선택 시에도 같은 동작을 하는 기능 추가 예정
> Add: session storage 저장 함수 추가

- public/data/userData.json
- src/Pages/SavedQueries/SavedQueries.js
- src/Pages/UserInfo/AccountInfo.js
Refactor: AccountInfo Data 변경
- 기존 사용자 1명의 mockData를 사용하던 코드 → 
GET Method 이용하여 BE로부터 받은 response 이용하는 방식으로 변경
- userData 별도 분리
- class → className 오류 수정
기존 user 정보가 포함된 data.json 파일은 NavBar 코드와 연관되어 수정하지 않았습니다.
> Refactor: AccountInfo Data 변경

- package-lock.json
- package.json
- src/Components/Footer/Footer.js
- src/Pages/CRSP.js
- src/Pages/Components/CRSP/StepFour.js
- src/Pages/Components/CRSP/StepOne.js
- src/Pages/SignUp/Signup.js
날짜형식 변경, submit버튼 작동로직 구현, 버튼제거, 마우스 이벤트 오류해결
step1, signup 부분의 날짜가 UTC타입에서 기존 숫자 형태로 변환하여 출력되게 저장.
submit 버튼 내용 구현.
이메일 input 창 옆 Edit Preferences 버튼 제거.
datepicker 달력 클릭시에 안 꺼지던 마우스 이벤트가 꺼짐으로 설정
세션스토리지에서 자료를 호출하는데, 선언되기전에 사용되었다고 오류가 뜸.
이를 해결하기 위해서 어떻게 해야할지 고민중
> fix: 마우스 이벤트 오류 해결

- src/Pages/Components/Main/ContactMap.js
Fix: 지도 크기 수정
Fix: 지도 크기 수정 - containerStyle 추가
> Fix: 지도 크기 수정

- src/Pages/Components/CRSP/CodeLookup.js
- src/Pages/Components/CRSP/TableData.js
- src/config.js
Fix: favicon 오류 수정 및 redux 일부 수정
**[2020. 09. 02(수)]**
- API 주소 수정
- 파비콘 오류 수정
**[2020. 09. 02(수)]**
- API 주소 AWS 주소로 수정
- 파비콘 오류 수정
- redux 파일 초기 state값 sessionStorage로 수정
- 소셜 로그인 맞춰볼 예정
> Refactor: API 주소 수정

- src/config.js
- config.js 오류 수정
- SUBMIT_POINT가 두 번 선언되어있던 오류 수정
- .
> Fix: config.js 오류 수정

- src/Pages/Components/CRSP/StepFour.js
- src/Pages/SignUp/Signup.js
- src/config.js
modify: import 주소 통합 및 config 내 CRSP_SUBMIT 주소 추가
> modify: import 주소 통합 및 config 내 CRSP_SUBMIT 추가

- src/Pages/Components/CRSP/StepFour.js
- src/Pages/Components/CRSP/StepOne.js
submit 버튼을 눌렀을시에 해당 기능 구현완료.
아직 다운로드 기능은 구현되지 않음.
step2의 서치바 기능에서 인자값들이 넘어오지 않아서 호출하는 것만 완성.
그외 모든 기능은 정상 구현됨을 확인함.
> add: submit 버튼 기입 내용 발송구현 완료

- src/Components/Nav/Header/Header.js
- src/Components/Nav/Logout.js
- src/Components/Nav/MainNav.js
- src/Components/Nav/Nav.js
- src/config.js
**[2020. 09. 04(금)]**
- 로그인 시 상단 nav 바뀌지 않던 오류 수정
**[2020. 09. 04(금)]**
- 로그인 시 상단 nav 바뀌지 않던 오류 수정
> Fix: 로그인 시 상단 nav 바뀌지않던 오류 수정

- public/data/crsptab.json
- src/Pages/Components/Main/LatestNews.js
- src/Pages/Components/Main/PageHighlight.js
- src/Pages/SavedQueries/SavedQueries.js
- src/Pages/SignIn/SignIn.js
Fix: Query 오류 해결
Fix: Query 오류 해결
- SavedQuery가 없을 시 발생하던 map function 오류 해결 및 안내문구 추가
로그인 화면에서 email 혹은 password 미입력 시 alert 추가
엔터 키로 로그인 기능 추가
> Fix: Query 오류 해결

- src/Pages/Components/CRSP/CodeLookup.js
**[2020. 09 .04(금)]**
- stock code 저장하게 수정
**[2020. 09 .04(금)]**
- corp_code를 저장하던 것에서 stock code를 저장하게 수정
> Fix: stock code 저장하게 수정

- package-lock.json
- package.json
- src/Pages/Components/CRSP/StepFour.js
파일 다운로드를 위한 경로인 Link태그 제거 및 Filesaver 대체
PERMCO,  PERMNO를 STOCK_CODE로 변경
파일 접근 경로는 만들었으나 백엔드측에서 접근 불가능한 경로를 주어 접근불가로 판정.
진행 불가
> modify: Link태그 제거 및 Filesaver 대체

- src/Pages/Components/CRSP/CodeLookup.js
- src/Pages/Components/CRSP/Search.js
- src/Pages/Components/CRSP/TableData.js
**[2020. 09. 04(금)]**
- identifier 버튼 삭제
**[2020. 09. 04(금)]**
- identifier 버튼 삭제
- 안쓰는 state 삭제
> Modify: identifier 버튼 삭제

- public/data/inputlistrequire.json
> Fix: Complist 수정

- src/Pages/SavedQueries/SavedQueries.js
- src/Pages/UserInfo/AccountInfo.js
Refactor: reload 코드 추가
Refactor: reload 코드 추가
-일부 디바이스에서 새로운 배열을 반영하지 못해 Reload 함수를 추가
AccountInfo 페이지 링크 margin 추가
> Refactor: reload 코드 추가

- src/Pages/Components/CRSP/StepFour.js
step4 submit 버튼 내 호출순서 조정
alert 내용(요청하신 메일로 정상 발송되었습니다) 추가
alert내용 추가
> modify: step4 submit 버튼내 순서 조정

- src/Components/GoToTop/GoToTop.js
- src/Pages/SavedQueries/SavedQueries.js
- src/Pages/SignUp/Signup.js
- src/Pages/SignUp/Verification.js
- src/Pages/UserInfo/AccountInfo.js
Add: PhoneVerificationCode 추가
>Add: PhoneVerificationCode 추가
>Add: SavedQueries 삭제 시 reload code 추가
>향후 이용 가능한 GoToTop Component 추가
> Add: PhoneVerificationCode 추가

- src/Components/Nav/TopPanel.js
- src/Pages/UserInfo/AccountInfo.js
**[2020. 09. 07(월)]**
- 회원 정보 날짜 형식 수정
**[2020. 09. 07(월)]**
- 회원 정보 날짜 형식 수정
- 탑 패널 다른 페이지로 이동 시 열리지 않던 오류 수정
> Fix: 회원 정보 날짜 형식 수정

- public/data/querytemp.json
- src/Pages/SavedQueries/EachQueries.js
- src/Pages/SavedQueries/SavedQueries.js
- src/Pages/SignUp/Signup.js
- src/Pages/SignUp/Verification.js
Refactor: Verification 버튼 위치 조정
1. SignUp Verification 위치 조정
2. Query 임시 데이터 Json 파일 추가
3. SavedQueries Checkbox 개별 선택 코드 수정
> Refactor: Verification 버튼 위치 조정

- package.json
- public/data/crsptab.json
- public/data/inputlistrequire.json
- src/Pages/CRSP.js
- src/Pages/Components/CRSP/Search.js
- src/Pages/Components/CRSP/StepFour.js
- src/Pages/Components/CRSP/StepOne.js
- src/Pages/Components/CRSP/StepThree.js
- src/Pages/SignIn/SignIn.js
- src/Pages/SignUp/Signup.js
다운로드 기능 구현 완료.
영문 번역 진행
sign in "로그아웃 테스트" 제거
임한섭님의 요청에 따른 번역 진행
signup의 비밀번호 조건 문구 추가(기능은 아직 구현 안됨)
> modify: 다운로드 기능 구현 완료 및 영문 번역

- public/data/crsptab.json
- public/data/stepThreeCategory.json
- src/Pages/Components/CRSP/CodeLookup.js
- src/Pages/Components/CRSP/CodeLookupText.js
- src/Pages/Components/CRSP/Search.js
- src/Pages/Components/CRSP/SecondModalBody.js
- src/Pages/Components/CRSP/StepFour.js
- src/Pages/Components/CRSP/StepOne.js
- src/Pages/Components/CRSP/StepThree.js
- src/Pages/Components/CRSP/StepThreeContents.js
- src/Pages/Components/CRSP/StepThreeSelect.js
- src/Pages/SignIn/SignIn.js
- src/Pages/SignUp/Signup.js
- src/Pages/SignUp/Verification.js
영문 번역 요청에 따른 추가 진행 수정사항
crsp, signup, signin의 영문 내용을 한글로 수정
> modify: 영문번역 진행

- src/Pages/Components/CRSP/StepThreeContents.js
Refactor: Step3 TabCategory 조건 수정
Refactor: Step3 TabCategory 조건 수정
Tab 색상 변경 오류 수정
> Refactor: Step3 TabCategory 조건 수정

- src/Pages/Components/CRSP/StepFour.js
- src/Pages/Components/CRSP/StepOne.js
- src/Pages/SignUp/Signup.js
datepicker 한글화 번역
datepicker 한글화 번역
표기 방식이 년/월이 아니라 월/년으로 되어 있음.
> modify: datepicker 한글화 번역

- public/data/stepThreeCategory.json
- src/Pages/CRSP.js
- src/Pages/Components/CRSP/SecondModal.js
- src/Pages/Components/CRSP/StepFour.js
- src/Pages/Components/CRSP/StepOne.js
- src/Pages/Components/CRSP/StepThree.js
- src/Pages/Components/CRSP/StepThreeSelect.js
- src/Pages/Components/CRSP/StepThreeSelected.js
- src/Pages/Components/Main/SmallCRSP.js
- src/Pages/SavedQueries/EachQueries.js
- src/Pages/SavedQueries/SavedQueries.js
- src/Pages/SignUp/Signup.js
> modify: 임한섭님의 요청에 따른 코드삭제 및 번역 추가
